/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface DeleteInterface extends utils.Interface {
  functions: {
    "bitmap()": FunctionFragment;
    "deleteEntries()": FunctionFragment;
    "fillEntries()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "bitmap" | "deleteEntries" | "fillEntries"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bitmap", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deleteEntries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillEntries",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bitmap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillEntries",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Delete extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeleteInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bitmap(overrides?: CallOverrides): Promise<[BigNumber]>;

    deleteEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fillEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bitmap(overrides?: CallOverrides): Promise<BigNumber>;

  deleteEntries(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fillEntries(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bitmap(overrides?: CallOverrides): Promise<BigNumber>;

    deleteEntries(overrides?: CallOverrides): Promise<void>;

    fillEntries(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    bitmap(overrides?: CallOverrides): Promise<BigNumber>;

    deleteEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fillEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bitmap(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deleteEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fillEntries(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
