/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Groat } from "./Groat";
export * as factories from "./factories";
export { Groat__factory } from "./factories/Groat__factory";
